### ISSUE TITLE
missing entry log file

### ISSUE THREAD

**Issue by xanthian** [Luligabi1/MagicFungi#43] opened 2022-01-19 14:11 UTC
- magicfungi 0.6.2-BETA+1.18.1
        - 
 [Worker-Main-3/ERROR]: Couldn't parse loot table magicfungi:first_join_book com.google.gson.JsonSyntaxException: Missing entries

**Comment by Luligabi1** [comment] 2022-01-19 14:21
So, this is a bit of a bad timing haha. I've just released a new version (0.6.3-BETA) and couldn't reproduce this error there, so it should be fixed. If the error persists, please reopen this issue or create a new one :)

**Closed as completed by Luligabi1** 2022-01-19 14:21 UTC
